---
title: "All_Water"
output: html_document
date: "2024-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a pipleine using phyloseq

```{r}
library(ggplot2); packageVersion("ggplot2")
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ranacapa); packageVersion("ranacapa")
library(microbiome); packageVersion("microbiome")
library(ggpubr); packageVersion("ggpubr")
library(DEGreport); packageVersion("DEGreport")
library(dplyr)
library(stringr)

set.seed(1)
```



```{r}
library(stringr)
w_metadata <- read.delim('~/All_water/metadata.txt', row.names = 1)

w_otu_table_in <- read.table('~/All_water/seqtab_final.txt', sep = "\t", row.names = 1, header = T, check.names = F)
w_otu_table_in <- as.matrix(w_otu_table_in)


w_taxonomy <- readDNAStringSet('~/repsetspecies.fasta')
w_taxonomy <- as.data.frame(w_taxonomy)
w_tax <- rownames(w_taxonomy) %>% as.data.frame()
w_tax <- str_split_fixed(w_tax$., ";", 7) %>% as.data.frame()
w_tax1 <- str_split_fixed(w_tax$V1, " ", 2) %>% as.data.frame()

w_tax <- cbind(w_tax1, w_tax)
w_tax <- w_tax[-c(3,9)]
row.names(w_tax) <- w_tax$V1
w_tax <- w_tax[-c(1)]
colnames(w_tax) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus")
w_tax <- as.matrix(w_tax)

library(ape); packageVersion("ape")

w_tree <- read.tree("~/All_water/aligned.tre")
w_random_tree <- rtree(ntaxa(w_tree), rooted = T, tip.label = taxa_names(w_tree))

w_ps <- phyloseq(otu_table(w_otu_table_in, taxa_are_rows=T), 
               sample_data(w_metadata), 
               tax_table(w_tax))

w_ps <- phyloseq::subset_taxa(w_ps, Domain != "NA")
w_ps <- phyloseq::subset_taxa(w_ps, Phylum != "NA")

w_tips <- w_random_tree$tip.label
w_tips <- as.data.frame(w_tips)

w_dd <- w_tips %>% tidyr::extract(w_tips, into = c("tips", "col2"), "^(.*?_.*?)_(.*)$")

w_dd <- w_dd[-c(2)]

w_new_tips <- as.vector(w_dd)
w_new_tips <- unlist(w_new_tips$tips)

w_random_tree$tip.label <- w_new_tips

w_ps <- merge_phyloseq(w_ps, w_random_tree)
```


You have now made a phyloseq object. Now look at whether the samples need rarefied

```{r}
w_ps <- phyloseq::subset_taxa(w_ps, Family != "Mitochondria")
w_ps <- phyloseq::subset_taxa(w_ps, Class != "Chloroplast")
w_ps <- phyloseq::subset_taxa(w_ps, Domain != "NA")


sort(sample_sums(w_ps))

#If I cut off the samples at 5000 reads, I will lose 14 samples. To do this, I will rarefy to 80% of 5000, so rarefy to 4000 reads

w_rare_ps <- rarefy_even_depth(w_ps, 2000, rngseed = T)

#11 samples removed because too low
```


```{r}
w_ordpcw <- ordinate(w_rare_ps, "PCoA", "unifrac", weighted = T)
w_ordpcunw <- ordinate(w_rare_ps, "PCoA", "unifrac", weighted = F)

weight <- plot_ordination(w_rare_ps, w_ordpcw, color = "Type") + geom_point(size = 3) + theme_bw()+ theme(legend.position = "bottom", legend.text = element_text(size = 12), legend.title = element_text(size = 14), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10)) + guides(color = guide_legend(nrow = 1, byrow = T))  + stat_ellipse(aes(color = Type, group = Type))
unweight <- plot_ordination(w_rare_ps, w_ordpcunw, color = "Type") + geom_point(size = 3) + theme_bw()+ theme( axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))+ theme(legend.position = "none")  + stat_ellipse(aes(color = Type, group = Type))

ggarrange(unweight, weight, nrow = 2)

ggsave("~/All_Water/manuscript_3.5.png", units = "cm", width = 25, height = 30)

```






